#!/usr/bin/env bash

# A rebuild script that commits on a successful build
set -e

# cd to your config dir
pushd ~/.config/nixos/

# Edit your config
$EDITOR debbie.nix

# Early return if no changes were detected (thanks @singiamtel!)
if git diff --quiet '*.nix'; then
  echo "No changes detected, exiting."
  popd
  exit 0
fi

# Autoformat your nix files
alejandra . &>/dev/null ||
  (
    alejandra .
    echo "formatting failed!" && exit 1
  )

# Shows your changes
git diff -U0 '*.nix'

echo "NixOS Rebuilding..."

# Rebuild, output simplified errors, log trackebacks
sudo nixos-rebuild switch &>nixos-switch.log || (cat nixos-switch.log | grep --color error && exit 1)

# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Commit all changes witih the generation metadata
git commit -am "$current"

# Push the changes to your remote repository
git push

# Back to where you were
popd

notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
